version: '3.8'
services:

    products-frontend:
        container_name: products-frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        volumes:
            - './frontend:/app'
        ports:
            - 1000:3000
        environment:
            - CHOKIDAR_USEPOLLING=true
        networks:
            - aenima-net

    products-backend:
        container_name: products-backend
        build:
            context: ./backend
            dockerfile: Dockerfile
        restart: unless-stopped
        environment:
            SERVICE_NAME: producTest
            SERVICE_TAGS: dev
        working_dir: /var/www/html
        volumes:
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./backend:/var/www/html
        networks:
            - aenima-net

    products-api:
        image: nginx:alpine
        container_name: products-api
        restart: unless-stopped
        ports:
            - "3000:80"
            - "443:443"
        volumes:
            - ./backend:/var/www/html
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - aenima-net

    db:
        image: mysql:5.7
        container_name: db
        restart: unless-stopped
        ports:
            - "3306"
        environment:
            MYSQL_DATABASE: aenima_test
            MYSQL_USER: demo
            MYSQL_PASSWORD: demo1234
            MYSQL_ROOT_PASSWORD: rootdemo1234
        volumes:
            - mysqldata:/var/lib/mysql/
        networks:
            - aenima-net

    db-admin:
        image: phpmyadmin:latest
        container_name: db-admin
        links:
            - db
        ports:
            - "8000:80"
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
        networks:
            - aenima-net

networks:
    aenima-net:
        driver: bridge

volumes:
    mysqldata:
        driver: local